#spring:
#  application:
#    name: "detail-service"
#  profiles:
#    active: "default"
#  cloud:
#    config:
#      uri: "http://localhost:8888"


spring:
  application:
    name: "detail-service"
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: "http://localhost:9411"

hystrix:
  share-security-context: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: "http://localhost:8761/eureka/"

server:
  port: 8102

logging:
  file: "detailservice/logs/detailservice.log"
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.springliquibase: DEBUG
