#spring:
#  application:
#    name: "zipkin-service"
#  profiles:
#    active: "default"
#  cloud:
#    config:
#      uri: "http://localhost:8888"


spring:
  application:
    name: "zipkin-service"

server:
  port: 9411

# https://github.com/openzipkin/zipkin/issues/2043
management:
  metrics:
    web:
      server:
        auto-time-requests: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: "http://localhost:8761/eureka/"

logging:
  file: "zipkinservice/logs/zipkinservice.log"
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.springliquibase: DEBUG
